export const emoji = [
  // 开心类
  { name: "微笑", emoji: "😊" },
  { name: "大笑", emoji: "😄" },
  { name: "露齿笑", emoji: "😃" },
  { name: "开心", emoji: "😀" },
  { name: "眯眼笑", emoji: "😁" },
  { name: "笑哭", emoji: "😂" },
  { name: "笑出眼泪", emoji: "🤣" },
  { name: "得意", emoji: "😎" },
  { name: "星星眼", emoji: "🤩" },
  { name: "飞吻", emoji: "😘" },
  { name: "亲亲", emoji: "😗" },
  { name: "眨眼", emoji: "😉" },
  { name: "花痴", emoji: "🥰" },
  { name: "色", emoji: "😍" },
  { name: "调皮", emoji: "😜" },
  { name: "吐舌", emoji: "😛" },
  { name: "调皮吐舌", emoji: "😝" },
  { name: "舔", emoji: "😋" },
  { name: "害羞", emoji: "😊" },
  { name: "脸红", emoji: "😳" },
  { name: "思考", emoji: "🤔" },
  { name: "嘘", emoji: "🤫" },
  { name: "闭嘴", emoji: "🤐" },
  { name: "困", emoji: "😴" },
  { name: "流口水", emoji: "🤤" },
  { name: "睡", emoji: "😪" },
  { name: "累", emoji: "😫" },
  { name: "疲惫", emoji: "😩" },
  { name: "打哈欠", emoji: "🥱" },

  // 难过类
  { name: "难过", emoji: "😢" },
  { name: "大哭", emoji: "😭" },
  { name: "委屈", emoji: "😞" },
  { name: "失望", emoji: "😔" },
  { name: "沮丧", emoji: "😟" },
  { name: "担心", emoji: "😕" },
  { name: "皱眉", emoji: "🙁" },
  { name: "不开心", emoji: "☹️" },
  { name: "痛苦", emoji: "😣" },
  { name: "绝望", emoji: "😖" },
  { name: "可怜", emoji: "🥺" },

  // 生气类
  { name: "生气", emoji: "😠" },
  { name: "愤怒", emoji: "😡" },
  { name: "发怒", emoji: "🤬" },
  { name: "抓狂", emoji: "🤯" },
  { name: "翻白眼", emoji: "🙄" },
  { name: "冷漠", emoji: "😒" },
  { name: "无语", emoji: "😑" },
  { name: "面无表情", emoji: "😐" },

  // 惊讶类
  { name: "惊讶", emoji: "😲" },
  { name: "震惊", emoji: "😮" },
  { name: "目瞪口呆", emoji: "😯" },
  { name: "害怕", emoji: "😨" },
  { name: "恐惧", emoji: "😱" },
  { name: "担心", emoji: "😰" },
  { name: "焦虑", emoji: "😥" },
  { name: "冷汗", emoji: "😓" },
  { name: "困惑", emoji: "😦" },
  { name: "困惑2", emoji: "😧" },

  // 其他
  { name: "生病", emoji: "🤒" },
  { name: "受伤", emoji: "🤕" },
  { name: "恶心", emoji: "🤢" },
  { name: "呕吐", emoji: "🤮" },
  { name: "打喷嚏", emoji: "🤧" },
  { name: "戴口罩", emoji: "😷" },
  { name: "发烧", emoji: "🤒" },
  { name: "热", emoji: "🥵" },
  { name: "冷", emoji: "🥶" },
  { name: "头晕", emoji: "😵" },
  { name: "晕", emoji: "🥴" },
  { name: "小丑", emoji: "🤡" },
  { name: "牛仔", emoji: "🤠" },
  { name: "庆祝", emoji: "🥳" },
  { name: "书呆子", emoji: "🤓" },
  { name: "怀疑", emoji: "🤨" },
  { name: "思考2", emoji: "🧐" },
  { name: "拥抱", emoji: "🤗" },
  { name: "捂嘴", emoji: "🤭" },
  { name: "说谎", emoji: "🤥" },
  { name: "沉默", emoji: "😶" },
  { name: "尴尬", emoji: "😬" },
  { name: "翻白眼2", emoji: "🙄" },
  { name: "天使", emoji: "😇" },
  { name: "倒脸", emoji: "🙃" },
  { name: "正常", emoji: "🙂" },
  { name: "疯狂", emoji: "🤪" },
];

// 按分类导出
export const emojiCategories = {
  happy: emoji.filter((e) =>
    [
      "微笑",
      "大笑",
      "露齿笑",
      "开心",
      "眯眼笑",
      "笑哭",
      "笑出眼泪",
      "得意",
      "星星眼",
      "飞吻",
      "亲亲",
      "眨眼",
      "花痴",
      "色",
      "调皮",
      "吐舌",
      "调皮吐舌",
      "舔",
      "害羞",
      "脸红",
    ].includes(e.name)
  ),
  sad: emoji.filter((e) =>
    [
      "难过",
      "大哭",
      "委屈",
      "失望",
      "沮丧",
      "担心",
      "皱眉",
      "不开心",
      "痛苦",
      "绝望",
      "可怜",
    ].includes(e.name)
  ),
  angry: emoji.filter((e) =>
    [
      "生气",
      "愤怒",
      "发怒",
      "抓狂",
      "翻白眼",
      "冷漠",
      "无语",
      "面无表情",
    ].includes(e.name)
  ),
  surprised: emoji.filter((e) =>
    [
      "惊讶",
      "震惊",
      "目瞪口呆",
      "害怕",
      "恐惧",
      "担心",
      "焦虑",
      "冷汗",
      "困惑",
      "困惑2",
    ].includes(e.name)
  ),
  other: emoji.filter(
    (e) =>
      ![
        "微笑",
        "大笑",
        "露齿笑",
        "开心",
        "眯眼笑",
        "笑哭",
        "笑出眼泪",
        "得意",
        "星星眼",
        "飞吻",
        "亲亲",
        "眨眼",
        "花痴",
        "色",
        "调皮",
        "吐舌",
        "调皮吐舌",
        "舔",
        "害羞",
        "脸红",
        "难过",
        "大哭",
        "委屈",
        "失望",
        "沮丧",
        "担心",
        "皱眉",
        "不开心",
        "痛苦",
        "绝望",
        "可怜",
        "生气",
        "愤怒",
        "发怒",
        "抓狂",
        "翻白眼",
        "冷漠",
        "无语",
        "面无表情",
        "惊讶",
        "震惊",
        "目瞪口呆",
        "害怕",
        "恐惧",
        "困惑",
      ].includes(e.name)
  ),
};
